```{r}
rm(list = ls())

PAQUETES <- c("dplyr","tidyverse","ggplot2","eurostat","readxl")

for (el in PAQUETES){
  if (!require(el, character.only = TRUE)) {
    install.packages(el, repos = "https://cloud.r-project.org")
    require(el, character.only = TRUE)
  }
}
```

```{r}
# Path to the dictionary fil
file_path <- paste0("./dictionaries/","decoding_dict",".xlsx")

# Get a list of all sheet names
sheet_names <- excel_sheets(file_path)

# Load each dictionary sheet
dictionary_df <- lapply(sheet_names, function(sheet) {
  read_excel(file_path, sheet = sheet, col_types = c("code" = "text", "name" = "text"))
}) %>% bind_rows()
dictionary <- setNames(dictionary_df$name, dictionary_df$code)

#load EU country names
EU_countries<-read_excel("./dictionaries/EU_countries.xlsx" ) %>% 
  rename(country_code=code,country_name=name)
EU_Countries_names_dict<- setNames(EU_countries$country_name, EU_countries$country_code)


#function to load and save data
load_data <- function(series,alias,dictionary,sheet_names){
  #load data
  data <- get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code))) %>% 
  filter(!is.na(values)) #filter out NAs
  #recode columns
  for (sheet in sheet_names){

    if (sheet %in% colnames(data)){
        data <- data %>% 
        mutate(!!sym(sheet) := recode(!!sym(sheet), !!!dictionary))
        ##!!! splits a vector into individual arguments for a function
        ## !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
    }
  }
  
  save(data, file = paste0("./data/",alias, ".RData"))
  print(paste0("series ",series," ", alias, " loaded"))
  rm(data)
  gc()
}
```

loading data
```{r}
statistics<-read_excel("./loading_statistics.xlsx")

for (ii in 1:nrow(statistics)) {
  load_data(statistics$code[ii],statistics$alias[ii],dictionary,sheet_names)
}


```

##1. Material living conditions
Average rating of satisfaction by domain, sex, age and educational attainment level
```{r}
datasets=c("ilc_pw01","ilc_pw05")
EU_countries<-read_excel("./dictionaries/EU_countries.xlsx" ) %>% 
  rename(country_code=code,country_name=name)
EU_Countries_names_dict<- setNames(EU_countries$country_name, EU_countries$country_code)

data_01 <-get_eurostat(datasets[1],
                    filters=list(geo=pull(EU_countries,country_code))) #read data for the 27 only
data_02 <-get_eurostat(datasets[2],
                    filters=list(geo=pull(EU_countries,country_code))) #read data for the 27 only

# merge both datasets
data_01 %>% 
  # mutate(lev_satis=NA ) %>% 
  bind_rows(data_02) -> satisfaction

sheets=c("age","isced11","indic_wb")
for (sheet in sheets) {
  dict <-read_excel(paste0("./dictionaries/","ilc_pw05",".xlsx"),sheet=sheet)
  replacement_dict <- setNames(dict$name, dict$code)
  satisfaction <- satisfaction %>% 
  mutate(!!sym(sheet) := recode(!!sym(sheet), !!!replacement_dict))
  ##!!! splits a vector into individual arguments for a function
  ## !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
}

satisfaction %>% 
  mutate(
    sex = recode(sex,"F"="Female","M"="Male","T"="Total"),
    country_name =recode(geo,!!!EU_Countries_names_dict),
    unit = recode(unit,"RTG"="Rating","PC"="Percentage")
    ) %>% 
  rename(indicator=indic_wb,
         education=isced11) -> satisfaction_export

save(exporting_data, file = paste0("./data/","satisfaction", ".RData"))


```

income of households, regional  
```{r}
dataset="nama_10r_2hhinc"
NUTS2<-read_excel("./dictionaries/NUTS2.xlsx" ) %>% 
  rename(geo=code)

income <-get_eurostat(dataset)
income %>% 
  mutate(country_code=substr(geo,1,2)) %>% 
  filter(country_code %in% EU_countries$country_code) %>% 
  filter(nchar(geo)==4) %>%   #only nuts 2 regions
  filter(direct=="BAL") %>%  #balance
  filter(unit=="EUR_HAB") %>% #eur per habitant
  filter(na_item=="B5N") %>% #income 
  left_join(NUTS2,by="geo") %>% 
  left_join(EU_countries,by=c("country_code")) %>% 
  mutate(date = TIME_PERIOD) %>% 
  select(-c(direct,na_item)) ->income_export

  

```
underemployment
```{r}
datasets=c("ilc_lvhl11")
EU_countries<-read_excel("./dictionaries/EU_countries.xlsx" ) %>% 
  rename(country_code=code,country_name=name)
EU_Countries_names_dict<- setNames(EU_countries$country_name, EU_countries$country_code)

underemployment <-get_eurostat(datasets[1],
                    filters=list(geo=pull(EU_countries,country_code)))

sheets=c("age","sex")
for (sheet in sheets) {
  dict <-read_excel(paste0("./dictionaries/","decoding_dict",".xlsx"),sheet=sheet)
  replacement_dict <- setNames(dict$name, dict$code)
  underemployment <- underemployment %>% 
  mutate(!!sym(sheet) := recode(!!sym(sheet), !!!replacement_dict))
  ##!!! splits a vector into individual arguments for a function
  ## !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
}

```
```{r}
recoding <- funct(dataset,dictionary){
  sheets<- excel_sheets(paste0("./dictionaries/",dictionary,".xlsx"))
  

  dict <-read_excel(paste0("./dictionaries/",dictionary,".xlsx"),sheet=sheet)
  colums<- colnames(dataset)
  for column_name in column {
    
  }
  replacement_dict <- setNames(dict$name, dict$code)
  underemployment <- underemployment %>% 
  mutate(!!sym(sheet) := recode(!!sym(sheet), !!!replacement_dict))
  ##!!! splits a vector into individual arguments for a function
  ## !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
}
```

```{r}
# Path to the Excel fil
file_path <- paste0("./dictionaries/","decoding_dict",".xlsx")

# Get a list of all sheet names
sheet_names <- excel_sheets(file_path)

# Load each sheet into a data frame
dictionary_df <- lapply(sheet_names, function(sheet) {
  read_excel(file_path, sheet = sheet, col_types = c("code" = "text", "name" = "text"))
}) %>% bind_rows()
dictionary <- setNames(dictionary_df$name, dictionary_df$code)



```


```{r}
save(satisfaction_export,income_export, file = paste0("./data/","data", ".RData"))

```

NOTA AL CARGAR_ QUITARSE LAS FILAS CON NA EN VALUES PARA AHORRAR ESPACIO


material living conditions
```{r}
datasets=c("ilc_pw01","ilc_pw05")
EU_countries<-read_excel("./dictionaries/EU_countries.xlsx" ) %>% 
  rename(country_code=code,country_name=name)
EU_Countries_names_dict<- setNames(EU_countries$country_name, EU_countries$country_code)

data_01 <-get_eurostat(datasets[1],
                    filters=list(geo=pull(EU_countries,country_code))) #read data for the 27 only
data_02 <-get_eurostat(datasets[2],
                    filters=list(geo=pull(EU_countries,country_code))) #read data for the 27 only

# merge both datasets
data_01 %>% 
  # mutate(lev_satis=NA ) %>% 
  bind_rows(data_02) %>% 
  mutate(indicator="satisfaction")-> satisfaction


ends_meet <-get_eurostat("ilc_mdes09",
                    filters=list(geo=pull(EU_countries,country_code))) %>% 
  mutate(indicator="ends")


```

Productive activity
```{r}
underemployment <-get_eurostat("ilc_lvhl11",
                    filters=list(geo=pull(EU_countries,country_code))) %>% 
  mutate(indicator="underemployment")
```

health 
```{r}
series <-"hlth_silc_10"
self_health <- get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code)))

series<-"hlth_ehis_pe2e"
time_health_enhancing <-get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code)))
```

education
```{r}
# care, digital skills is too large

series <-"edat_aes_l21"
alias <-"foreing_lang"
foreign_lang<-get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code))) %>% 
  filter(!is.na(values))



series <-"edat_aes_l21"
alias <-"foreing_lang"
load_data(series,alias,dictionary,sheet_names)


```
leisure and social interactions
```{r}

series <-"ilc_scp10"
get_together<-get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code)))

series <-"ilc_scp10"
ask_help<-get_together<-get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code)))

series <-"ilc_scp01"
activities<-get_together<-get_eurostat(series,
                    filters=list(geo=pull(EU_countries,country_code)))
```
safety
```{r}

```

